import React, { useState } from 'react';
import { Deck, Card } from '../types';
import { X, Sparkles, Loader2, CheckCircle2, BookOpen, Layers } from 'lucide-react';
import { sounds } from '../utils/audio';

interface AiDeckMakerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onDeckGenerated: (newDeck: Deck) => void;
}

export const AiDeckMakerModal: React.FC<AiDeckMakerModalProps> = ({
  isOpen,
  onClose,
  onDeckGenerated,
}) => {
  const [topic, setTopic] = useState('');
  const [level, setLevel] = useState('C1');
  const [cardCount, setCardCount] = useState(5);
  const [isLoading, setIsLoading] = useState(false);
  const [generatedPreview, setGeneratedPreview] = useState<{ title: string; category: string; description: string; cards: Partial<Card>[] } | null>(null);

  if (!isOpen) return null;

  const quickTopics = [
    'Tech Product Architecture & Cloud',
    'Executive Negotiation & Persuasion',
    'Medical & Clinical Diagnostics',
    'Environmental Sustainability & ESG',
    'Philosophical & Ethical Frameworks',
  ];

  const handleGenerate = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!topic.trim() || isLoading) return;

    setIsLoading(true);
    setGeneratedPreview(null);

    try {
      const res = await fetch('/api/ai/generate-deck', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topic.trim(),
          count: cardCount,
          level,
        }),
      });

      const data = await res.json();
      if (data && data.deck) {
        setGeneratedPreview(data.deck);
        sounds.playRating('good');
      }
    } catch (err) {
      console.error('Failed to generate deck via AI:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveDeck = () => {
    if (!generatedPreview) return;

    const cards: Card[] = (generatedPreview.cards || []).map((c, idx) => ({
      id: `card-ai-${Date.now()}-${idx}`,
      word: c.word || 'Vocabulary',
      phonetic: c.phonetic || `/${(c.word || '').toLowerCase()}/`,
      partOfSpeech: (c.partOfSpeech as Card['partOfSpeech']) || 'Adjective',
      definition: c.definition || 'Clear definition',
      vietnameseMeaning: c.vietnameseMeaning || 'Ý nghĩa tiếng Việt',
      exampleSentence: c.exampleSentence || `“Contextual sentence illustrating ${c.word}.”`,
      usageContext: c.usageContext || 'Contemporary Usage',
      rootOrigin: c.rootOrigin || 'Etymology',
      synonyms: c.synonyms || [],
      easeFactor: 2.5,
      intervalDays: 1,
      repetitions: 0,
      dueDate: new Date().toISOString(),
      status: 'new',
    }));

    const newDeck: Deck = {
      id: `deck-ai-${Date.now()}`,
      title: generatedPreview.title || topic,
      category: 'Specialized',
      level: level as Deck['level'],
      description: generatedPreview.description || `Targeted high-yield flashcards generated by AI on ${topic}.`,
      cardCount: cards.length,
      dueCount: cards.length,
      masteryRate: 0,
      lastReviewed: 'Just created',
      tags: ['AI Generated', level, topic],
      cards,
    };

    sounds.playRating('easy');
    onDeckGenerated(newDeck);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/40 backdrop-blur-xs">
      <div 
        className="w-full max-w-2xl bg-white rounded-3xl shadow-2xl border border-slate-200 p-6 sm:p-8 overflow-hidden animate-fadeIn max-h-[90vh] flex flex-col justify-between"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100">
          <div className="flex items-center space-x-2.5">
            <div className="w-9 h-9 rounded-2xl bg-gradient-to-tr from-violet-600 to-indigo-600 text-white flex items-center justify-center shadow-xs">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900">AI Instant Deck Maker</h2>
              <p className="text-xs text-slate-500">Synthesize targeted spaced repetition decks in seconds.</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content Body */}
        <div className="overflow-y-auto py-4 space-y-5">
          {!generatedPreview ? (
            <form onSubmit={handleGenerate} className="space-y-4">
              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">
                  Topic, Discipline, or Paste Reading Material *
                </label>
                <textarea
                  required
                  rows={3}
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g. Behavioral Economics & Game Theory, or paste an article excerpt..."
                  className="w-full p-3.5 rounded-2xl border border-slate-200 text-sm text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 resize-none"
                />
              </div>

              {/* Quick Topic Chips */}
              <div>
                <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block mb-1.5">
                  Popular Suggested Disciplines
                </span>
                <div className="flex flex-wrap gap-1.5">
                  {quickTopics.map((t) => (
                    <button
                      key={t}
                      type="button"
                      onClick={() => setTopic(t)}
                      className="px-2.5 py-1 rounded-lg text-xs font-medium bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors cursor-pointer"
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3 pt-2">
                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1">
                    CEFR Proficiency Target
                  </label>
                  <select
                    value={level}
                    onChange={(e) => setLevel(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs text-slate-900 bg-white"
                  >
                    <option value="B1">B1 Intermediate</option>
                    <option value="B2">B2 Upper Intermediate</option>
                    <option value="C1">C1 Advanced (Recommended)</option>
                    <option value="C2">C2 Native Polyglot</option>
                  </select>
                </div>

                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1">
                    Number of Cards
                  </label>
                  <select
                    value={cardCount}
                    onChange={(e) => setCardCount(Number(e.target.value))}
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs text-slate-900 bg-white"
                  >
                    <option value={5}>5 Cards (Quick Sprint)</option>
                    <option value={8}>8 Cards (Deep Dive)</option>
                  </select>
                </div>
              </div>

              <div className="pt-3">
                <button
                  type="submit"
                  disabled={!topic.trim() || isLoading}
                  className="w-full py-3 rounded-2xl bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-200 text-white font-bold text-xs shadow-md shadow-indigo-500/20 transition-all cursor-pointer flex items-center justify-center space-x-2"
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      <span>Synthesizing Lexicon & Phonetics via AI...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      <span>Generate Smart Flashcards</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          ) : (
            /* Generated Deck Preview */
            <div className="space-y-4">
              <div className="p-4 rounded-2xl bg-indigo-50/70 border border-indigo-100 flex items-start justify-between">
                <div>
                  <h3 className="font-bold text-base text-slate-900">
                    {generatedPreview.title}
                  </h3>
                  <p className="text-xs text-slate-600 mt-0.5">
                    {generatedPreview.description}
                  </p>
                </div>
                <span className="px-2 py-0.5 rounded-full text-xs font-bold bg-indigo-600 text-white shrink-0">
                  {generatedPreview.cards?.length || 0} Cards
                </span>
              </div>

              <div className="space-y-2.5 max-h-[300px] overflow-y-auto pr-1">
                {generatedPreview.cards?.map((card, i) => (
                  <div key={i} className="p-3.5 rounded-xl border border-slate-200 bg-slate-50/50 space-y-1">
                    <div className="flex items-center justify-between">
                      <div className="flex items-baseline space-x-2">
                        <span className="font-bold text-sm text-slate-900">{card.word}</span>
                        <span className="text-xs font-mono text-slate-400">{card.phonetic}</span>
                        <span className="text-xs font-semibold text-indigo-700">• {card.vietnameseMeaning}</span>
                      </div>
                      <span className="text-[10px] font-semibold bg-white border border-slate-200 px-1.5 py-0.2 rounded text-slate-600">
                        {card.partOfSpeech}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600">{card.definition}</p>
                    <p className="text-[11px] text-slate-500 italic">“{card.exampleSentence}”</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {generatedPreview && (
          <div className="flex items-center justify-between pt-4 border-t border-slate-100">
            <button
              type="button"
              onClick={() => setGeneratedPreview(null)}
              className="px-4 py-2 text-xs font-semibold text-slate-600 hover:text-slate-800"
            >
              ← Edit Prompt
            </button>
            <button
              type="button"
              onClick={handleSaveDeck}
              className="px-6 py-2.5 rounded-xl bg-slate-900 hover:bg-indigo-600 text-white font-semibold text-xs shadow-md transition-colors cursor-pointer flex items-center space-x-2"
            >
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>Save Deck to Library</span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
